using UnityEngine;

public class GolpeJugador : MonoBehaviour
{
    [Header("Configuraci칩n del ataque")]
    [SerializeField] private int dano = 5;
    [SerializeField] private Collider2D colliderGolpe;

    private void OnTriggerEnter2D(Collider2D other)
    {

        if (other.CompareTag("enemigo"))
        {
            EnemOso oso = other.GetComponent<EnemOso>();
            if (oso != null)
            {
                oso.RecibirDanio(dano);
                Debug.Log($"[GOLPE] 游눤 Impacto al Oso. Da침o: {dano}");
            }

            Tanque tanque = other.GetComponent<Tanque>();
            if (tanque != null)
            {
                tanque.RecibirDa침o(dano);
                Debug.Log($"[GOLPE] 游눤 Impacto al Tanque. Da침o: {dano}");
            }

            Tanque2 tanque2 = other.GetComponent<Tanque2>();
            if (tanque2 != null)
            {
                tanque2.RecibirDa침o(dano);
                Debug.Log($"[BALA] 游눤 Impacto al Tanque2. Da침o enviado: {dano}");
            }

            EnemYeti enemYeti = other.GetComponent<EnemYeti>();
            if (enemYeti != null)
            {
                enemYeti.RecibirDa침o(dano);
                Debug.Log($"[BALA] 游눤 Impacto al Yeti. Da침o enviado: {dano}");
            }

            EnemigoEscudero escudero = other.GetComponent<EnemigoEscudero>();
            if (escudero != null)
            {
                escudero.RecibirDa침o(dano);
                Debug.Log($"[BALA] 游눤 Impacto al Escudero. Da침o enviado: {dano}");
            }
        }
    }
}
